// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using timpossible.Models;

namespace timpossible.Migrations
{
    [DbContext(typeof(ImpossibleContext))]
    [Migration("20171126140724_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("timpossible.Models.Task", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<DateTime>("ClosingDate");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Currency");

                    b.Property<string>("Description");

                    b.Property<double>("Lat");

                    b.Property<string>("Location");

                    b.Property<double>("Lon");

                    b.Property<string>("NegotiationMarker");

                    b.Property<string>("Owner");

                    b.Property<string>("PaymentTerms");

                    b.Property<double>("Radius");

                    b.Property<double>("Renumeration");

                    b.Property<string>("Status");

                    b.Property<DateTime>("TargetDate");

                    b.Property<string>("Title");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
