// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using timpossible.Models;

namespace timpossible.Migrations
{
    [DbContext(typeof(ImpossibleContext))]
    [Migration("20171126143059_photoadded")]
    partial class photoadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("timpossible.Models.Task", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<DateTime>("ClosingDate");

                    b.Property<string>("CoverPhoto");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Currency");

                    b.Property<string>("Description");

                    b.Property<double>("Lat");

                    b.Property<string>("Location");

                    b.Property<double>("Lon");

                    b.Property<string>("NegotiationMarker");

                    b.Property<string>("Owner");

                    b.Property<string>("PaymentTerms");

                    b.Property<double>("Radius");

                    b.Property<double>("Renumeration");

                    b.Property<string>("Status");

                    b.Property<DateTime>("TargetDate");

                    b.Property<string>("Title");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("timpossible.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Base");

                    b.Property<string>("BaseCurrency");

                    b.Property<string>("BillingAddress");

                    b.Property<string>("Bio");

                    b.Property<string>("Capabilities");

                    b.Property<string>("Country");

                    b.Property<string>("DisplayImage");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<string>("Grade");

                    b.Property<DateTime>("JoiningDate");

                    b.Property<DateTime>("LastVisitedDate");

                    b.Property<double>("Lat");

                    b.Property<string>("Location");

                    b.Property<double>("Lon");

                    b.Property<string>("Mobile");

                    b.Property<string>("NickName")
                        .IsRequired();

                    b.Property<int>("OverallRating");

                    b.Property<string>("Qualifications");

                    b.Property<string>("SecondName");

                    b.Property<string>("State");

                    b.Property<string>("Status");

                    b.Property<bool>("Tasker");

                    b.Property<int>("TasksCompleted");

                    b.Property<bool>("Verified");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
